# Generated by Django 2.2.21 on 2021-06-08 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_ttl', models.PositiveSmallIntegerField(default=1, verbose_name='Время жизни правила (в сутках)')),
                ('trows_on_page', models.PositiveSmallIntegerField(default=3, verbose_name='Число строк таблицы правил на странице')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Оригинальная ссылка')),
                ('alias', models.CharField(max_length=100, verbose_name='Алиас')),
                ('subpart', models.CharField(max_length=40, verbose_name='Субдомен')),
                ('expire_date', models.DateField(verbose_name='Дата удаления правила')),
                ('str_limit', models.PositiveSmallIntegerField(default=40, verbose_name='Число первых символов отображения оригинального URL в методе __str__')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время операции')),
                ('process', models.CharField(max_length=100, verbose_name='Имя процесса')),
                ('execute', models.TextField(verbose_name='Что выполнено')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Owner')),
                ('url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Url')),
            ],
        ),
    ]
