# Generated by Django 2.2.21 on 2021-05-07 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Оригинальный URL')),
                ('expire_date', models.DateField(verbose_name='Дата удаления правила')),
                ('short', models.CharField(max_length=100, verbose_name='Короткая cсылка')),
                ('subpart', models.CharField(max_length=40, verbose_name='Субдомен')),
                ('str_limit', models.PositiveSmallIntegerField(default=25, verbose_name='Число первых символов отображении оригинального URL в методе __str__')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.Session')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Url')),
            ],
        ),
    ]
