# Generated by Django 2.2.21 on 2021-05-07 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Url'),
        ),
    ]
