# Generated by Django 2.2.21 on 2021-05-08 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210508_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='url',
        ),
        migrations.AddField(
            model_name='owner',
            name='trows_on_page',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Число строк таблицы правил на странице'),
        ),
        migrations.AlterField(
            model_name='url',
            name='link',
            field=models.URLField(verbose_name='Оригинальная ссылка'),
        ),
        migrations.AlterField(
            model_name='url',
            name='str_limit',
            field=models.PositiveSmallIntegerField(default=40, verbose_name='Число первых символов отображения оригинального URL в методе __str__'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Owner')),
                ('url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Url')),
            ],
        ),
    ]
