# Generated by Django 2.2.21 on 2021-05-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210510_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='url_ttl',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Время жизни правила (в сутках)'),
        ),
    ]
